[input]
fasta_file = "/home/ab/run/her2_abag.fasta"
ag_pdb_file = "/home/ab/run/her2_ag.pdb"
[settings]
design_method = ["IgLM", "ReprogBERT", "PALM", "AbGPT"]
design_num = 10
pre_structure = true
docking = true
out_path = "/home/ab/run/output/"
